name: Check Pusher

on:
  push:
    branches:
      - main

jobs:
  check-pusher:
    runs-on: ubuntu-latest

    steps:
      - name: Check pusher
        if: github.actor != 'josuviteri'
        run: |
          echo "Error: Unauthorized push. Only josuviteri is allowed to push to this repository."
          exit 1
