name: Check Push User

on:
  push:
    branches:
      - main

jobs:
  check-push-user:
    runs-on: ubuntu-latest

    steps:
      - name: Check push user
        run: |
          push_user=$(git log -1 --format='%an' $GITHUB_SHA)
          if [ "$push_user" == "josuviteri" ]; then
            echo "Push by user 'josuviteri'."
            exit 0
          else
            echo "Push not by user 'josuviteri'."
            exit 1
          fi
